openapi: 3.0.3
info:
  title: 'Quote of the day Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/quote:
    get:
      summary: 'Get Random Quotes'
      operationId: getRandomQuotes
      description: "This Route Get a Random Quote from the Api and will return a status code of 200 if the quote is found\n\nOtherwise, the request will fail with a 404 error,and not quotes is found"
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    quote: 'Voluptatibus quibusdam sint non accusantium voluptate corporis numquam qui tempore ullam harum.'
                    author:
                      name: 'Ona Durgan Sr.'
                      picture:
                        large: 'https://randomuser.me/api/portraits/men/75.jpg'
                        medium: 'https://randomuser.me/api/portraits/med/men/75.jpg'
                        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/75.jpg'
                properties:
                  data:
                    type: object
                    properties:
                      quote:
                        type: string
                        example: 'Voluptatibus quibusdam sint non accusantium voluptate corporis numquam qui tempore ullam harum.'
                      author:
                        type: object
                        properties:
                          name:
                            type: string
                            example: 'Ona Durgan Sr.'
                          picture:
                            type: object
                            properties:
                              large:
                                type: string
                                example: 'https://randomuser.me/api/portraits/men/75.jpg'
                              medium:
                                type: string
                                example: 'https://randomuser.me/api/portraits/med/men/75.jpg'
                              thumbnail:
                                type: string
                                example: 'https://randomuser.me/api/portraits/thumb/men/75.jpg'
      tags:
        - Endpoints
      security: []
  '/api/quotes/{quotes_id}':
    get:
      summary: 'Get Quotes Based On an ID'
      operationId: getQuotesBasedOnAnID
      description: "This Route Get a Quote from the Api based on the ID given and will return a status code of 200 if the quote is found\n\nOtherwise, the request will fail with a 404 error, because no quote with that ID is found"
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    quote: 'Omnis ab facilis laborum deleniti illum et illo minima optio corrupti maxime minima repellendus.'
                    author:
                      name: 'Baby Farrell DVM'
                      picture:
                        large: 'https://randomuser.me/api/portraits/men/91.jpg'
                        medium: 'https://randomuser.me/api/portraits/med/men/91.jpg'
                        thumbnail: 'https://randomuser.me/api/portraits/thumb/men/91.jpg'
                properties:
                  data:
                    type: object
                    properties:
                      quote:
                        type: string
                        example: 'Omnis ab facilis laborum deleniti illum et illo minima optio corrupti maxime minima repellendus.'
                      author:
                        type: object
                        properties:
                          name:
                            type: string
                            example: 'Baby Farrell DVM'
                          picture:
                            type: object
                            properties:
                              large:
                                type: string
                                example: 'https://randomuser.me/api/portraits/men/91.jpg'
                              medium:
                                type: string
                                example: 'https://randomuser.me/api/portraits/med/men/91.jpg'
                              thumbnail:
                                type: string
                                example: 'https://randomuser.me/api/portraits/thumb/men/91.jpg'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: quotes_id
        description: 'The ID of the quotes.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/quotes/search/{quotes_author}':
    get:
      summary: 'Search Quotes with Author Names'
      operationId: searchQuotesWithAuthorNames
      description: "This Route Search for a Quote from the Api using author names this will return a status code of 200 if the quote with the author name is found\n\nOtherwise, the request will fail with a 404 error,and not quotes is found"
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      quote: 'How i became a man today by coding'
                      author:
                        name: 'Oluwademilade Abatan'
                        picture:
                          large: 'https://randomuser.me/api/portraits/men/78.jpg'
                          medium: 'https://randomuser.me/api/portraits/med/men/78.jpg'
                          thumbnail: 'https://randomuser.me/api/portraits/thumb/men/78.jpg'
                    -
                      quote: 'This is to test Whether the queues work'
                      author:
                        name: 'Demilade Abatan'
                        picture:
                          large: 'https://randomuser.me/api/portraits/women/79.jpg'
                          medium: 'https://randomuser.me/api/portraits/med/women/79.jpg'
                          thumbnail: 'https://randomuser.me/api/portraits/thumb/women/79.jpg'
                properties:
                  data:
                    type: array
                    example:
                      -
                        quote: 'How i became a man today by coding'
                        author:
                          name: 'Oluwademilade Abatan'
                          picture:
                            large: 'https://randomuser.me/api/portraits/men/78.jpg'
                            medium: 'https://randomuser.me/api/portraits/med/men/78.jpg'
                            thumbnail: 'https://randomuser.me/api/portraits/thumb/men/78.jpg'
                      -
                        quote: 'This is to test Whether the queues work'
                        author:
                          name: 'Demilade Abatan'
                          picture:
                            large: 'https://randomuser.me/api/portraits/women/79.jpg'
                            medium: 'https://randomuser.me/api/portraits/med/women/79.jpg'
                            thumbnail: 'https://randomuser.me/api/portraits/thumb/women/79.jpg'
                    items:
                      type: object
                      properties:
                        quote:
                          type: string
                          example: 'How i became a man today by coding'
                        author:
                          type: object
                          properties:
                            name:
                              type: string
                              example: 'Oluwademilade Abatan'
                            picture:
                              type: object
                              properties:
                                large:
                                  type: string
                                  example: 'https://randomuser.me/api/portraits/men/78.jpg'
                                medium:
                                  type: string
                                  example: 'https://randomuser.me/api/portraits/med/men/78.jpg'
                                thumbnail:
                                  type: string
                                  example: 'https://randomuser.me/api/portraits/thumb/men/78.jpg'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: quotes_author
        description: 'Optional parameter. The Author Name'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: Demilade
tags:
  -
    name: Endpoints
    description: ''
